---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r ready_file}
unzip("activity.zip")
act <- read.csv("activity.csv", sep = ",", header = T)
```
## What is mean total number of steps taken per day?
```{r histo_mean}
total_steps <- tapply(act$steps,act$date,sum,na.rm=T)
hist(total_steps, main = "Histogram of total steps", xlab = "Total Steps per day" )
mean(total_steps)
median(total_steps)
```


## What is the average daily activity pattern?
```{r daily_activity}
interval_mean <- tapply(act$steps, act$interval, mean, na.rm=T)
plot(unique(act$interval), interval_mean, type ="l", xlab = "Interval", ylab = "Average number of steps", main = "Average daily activity pattern") 
interval_mean[which(interval_mean==max(interval_mean))]
```


## Imputing missing values
```{r missing_values}
#copy dataset, store the interval mean in all the NA step records, sum by each day, histogram the total steps, mean, median
sum(is.na(act$steps))
act2 <- act
act2$steps <- replace(act2$steps, is.na(act2$steps), interval_mean)
total_steps2 <- tapply(act2$steps,act2$date,sum,na.rm=T)
hist(total_steps2, main = "Total Steps with replacement", ylab="Interval", xlab = "Total Steps")
mean(total_steps2)
median(total_steps2)
```

## Are there differences in activity patterns between weekdays and weekends?
```{r weekends}
act2$day_type <- as.factor(ifelse((weekdays(as.Date(act2$date))=="Saturday")|(weekdays(as.Date(act2$date))=="Sunday"),"weekend","weekday"))
# summary(act2$day_type)
aggdata <- aggregate(act2$steps, by = list(act2$interval, act2$day_type), FUN =mean)
library("lattice")
xyplot(aggdata$x~aggdata$Group.1|aggdata$Group.2, type = "l", layout = c(1,2), xlab = "Interval", ylab = "Number of Steps", main = "Average daily activity pattern by day type")

```

